
---
- name: Deploy AMQ on OCP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install AMQ Broker
      k8s:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        namespace: '{{ operator_namespace | default("openshift-operators") }}'
        definition:
          metadata:
            name: amq-broker-rhel8
          spec:
            channel: '{{ operator_channel | default("7.12.x") }}'
            name: redhat-amq-broker
            source: redhat-operators
            sourceNamespace: openshift-marketplace
      #  retries: 5  # Add retries if the Operator installation is flaky
      #  delay: 10   # Wait between retries
    - name: Wait for AMQ Broker Operator to be ready
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: '{{ operator_namespace | default("openshift-operators") }}'
        label_selectors:
          - operators.coreos.com/redhat-amq-broker.{{ operator_namespace | default("openshift-operators") }} # corrected label selector
      register: amq_operator_csv
      until: amq_operator_csv.resources | map(attribute='status.phase') | list | first == "Succeeded"
      retries: 30
      delay: 10
