- name: Install AMQ Broker Operator on OpenShift in 'artemis' namespace
  hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create namespace for AMQ Broker Operator
      k8s:
        api_version: v1
        kind: Namespace
        name: artemis
        state: present

    - name: Create OperatorGroup for AMQ Broker
      k8s:
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        namespace: artemis
        name: amq-broker-operatorgroup
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: amq-broker-operatorgroup
            namespace: artemis
          spec:
            targetNamespaces:
              - artemis

    - name: Subscribe to AMQ Broker Operator
      k8s:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        namespace: artemis
        name: amq-broker
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: amq-broker
            namespace: artemis
          spec:
            channel: 7.12.x
            name: amq-broker-rhel8
            source: redhat-operators
            sourceNamespace: openshift-marketplace



