
---
- name: Deploy AMQ on OCP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create namespace
      redhat.openshift.k8s:
        name: artemis
        api_version: v1
        kind: Namespace
        state: present

    - name: Create AMQ Broker Operator Subscription
      redhat.openshift.k8s:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        namespace: '{{ operator_namespace | default("openshift-operators") }}'
        definition:
          metadata:
            name: amq-broker-rhel8
          spec:
            channel: 7.12.x
            name: redhat-amq-broker
            source: redhat-operators
            sourceNamespace: openshift-marketplace

