---
- name: Deploy Keycloak on OCP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create namespace
      redhat.openshift.k8s:
        name: artemis
        api_version: v1
        kind: Namespace
        state: present
        
    - name: Create Operator OperatorGroup
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: keycloak
            namespace: openshift-operators
          spec:
            targetNamespaces:
            - artemis

    - name: Create Keycloak subscriptions
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            labels:
              operators.coreos.com/keycloak.openshift-operators: ''
            name: red-hat-build-of-keycloak-operator
            namespace: openshift-operators
          spec:
            channel: stable-v26
            installPlanApproval: Automatic
            name: rhbk-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            